### ISSUE TITLE
Exercise 3 - all links are broken

### ISSUE THREAD

**Issue by dani-lbnl** [KitwareMedical/CourseInBiomedicalImageAnalysisVisualizationAndArtificialIntelligence#5]
https://github.com/KitwareMedical/CourseInBiomedicalImageAnalysisVisualizationAndArtificialIntelligence/blob/master/3_Image_Filtering.ipynb

**Comment by thewtex** [comment]
@dani-lbnl thanks for the report!

Addressed in https://github.com/KitwareMedical/CourseInBiomedicalImageAnalysisVisualizationAndArtificialIntelligence/pull/6
